### ISSUE TITLE
opening http://localhost:3000/ throws error on client side

### ISSUE THREAD

**Issue by asantoso** [peerreynders/nitro-sse-counter#1]
URL.canParse is not a function

  at urlFromRequest (./.nitro/dev/index.mjs:762:14)
  at Object.handler (./.nitro/dev/index.mjs:766:15)
  at Object.handler (./node_modules/h3/dist/index.mjs:1675:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1885:7)

**Comment by peerreynders** [comment]
[`URL.canParse(input[, base])`](https://nodejs.org/api/url.html#urlcanparseinput-base) wasn't added until Node v19.9.0/v18.17.0. I've added an `engines` constraint in the `package.json` to reflect that.

The "on client side" makes no sense given that the client code is all under `src/client` with an entry point at `src/client/entry.js`; i.e. there is no reason for `src/server/url.ts` to be pulled into the client side bundle `public/main.js` (apart from that the client side code isn't TS transpiled, so the JS-runtime would fail on raw TS code).
